### ISSUE TITLE
Can't find "Server side support scripts for the Atom editor package"

### ISSUE THREAD

**Issue by mgraauw** [eXist-db/atom-existdb#52]
Automated install of server side scripts from Atom fails (don't know why).

The readme says "If this fails for any reason, install it manually by going to the eXistdb dashboard. In the package manager, search for an app called Server side support scripts for the Atom editor package and install it." - but I cannot find that package, it's also not listed on:
http://demo.exist-db.org/exist/apps/public-repo/index.html (eXist 4.3.1 + Atom 1.33.1x64)

Where does it live?

**Comment by duncdrum** [comment]
shows up ok for me, are you by any chance sitting behind a firewall with you exist-db instance, or anything else that might interfere with it calling home?
![screenshot 2019-01-07 at 14 56 44](https://user-images.githubusercontent.com/6205362/50771996-8a81e200-128c-11e9-966a-7e4d24b84230.png)

**Comment by duncdrum** [comment]
in any case you can build the .xar yourself from github: [https://github.com/eXist-db/atom-editor-support](https://github.com/eXist-db/atom-editor-support)

**Comment by mgraauw** [comment]
At home, not likely a firewall has to do with it. Cannot see the server side scripts in:
http://demo.exist-db.org/exist/apps/public-repo/public/apps.xml
either. Strange that you see them.

Building & installing the xar did the job - thanks! Atom does tell me I have 1.0.0 and there is a "newer" 0.2.9 server side support app, but if I ignore that, things work.

**Comment by RelativePrime** [comment]
Fwiw, I also do not see this package listed at http://exist-db.org/exist/apps/public-repo/index.html or http://demo.exist-db.org/exist/apps/public-repo/index.html nor does it show in search in dashboard.
