### ISSUE TITLE
Change dowload exist-syntax to use HTTPS iso SSH

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/atom-existdb#59]
To install the plugin, a working SSH/GIT connection is required:

![image](https://user-images.githubusercontent.com/1700062/51372711-5adda000-1afe-11e9-8a6a-140903cbd584.png)

This is caused by

https://github.com/eXist-db/atom-existdb/blob/6ac2fe6e727a5cc39ac40ea3792f92131b5280fa/package.json#L46

As I am behind a corporate firewall, SSH is blocked. Installing is impossible.

Requested change: use HTTPS connection in stead of SSH.

**Comment by duncdrum** [comment]
@wolfgangmm looks like another candidate for our big merging of xqlint forks?

@dizzzz agreed https from package.json makes sense.
